# Generated by Django 3.1 on 2020-09-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='homepage.Recipe'),
        ),
    ]
